In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,3,5,7,12])
a

array([ 1,  3,  5,  7, 12])

In [6]:
a[3]

np.int64(7)

In [7]:
a[3] = 10

In [8]:
a

array([ 1,  3,  5, 10, 12])

In [11]:
np.range(3,10)

AttributeError: module 'numpy' has no attribute 'range'

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linespace(0,1,11)

AttributeError: module 'numpy' has no attribute 'linespace'

In [14]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [19]:
n[0,1]

np.int64(2)

In [20]:
n[2] = [1,1,1]

In [21]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [22]:
n[:, 1] = [3,3,3]

In [23]:
n

array([[1, 3, 3],
       [4, 3, 6],
       [1, 3, 1]])

In [30]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [31]:
np.random.seed(2)
100 * np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [32]:
np.random.seed(2)
100 * np.random.randint(low=0, high=100, size=(5,2))

array([[4000, 1500],
       [7200, 2200],
       [4300, 8200],
       [7500,  700],
       [3400, 4900]])

In [33]:
a = np.arange(5)

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a + 1

array([1, 2, 3, 4, 5])

In [36]:
a * 100

array([  0, 100, 200, 300, 400])

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a >= 2

array([False, False,  True,  True,  True])

In [39]:
a.sum()

np.int64(10)

In [40]:
a.mean()

np.float64(2.0)

In [41]:
a.std()

np.float64(1.4142135623730951)